// <auto-generated />
using System;
using EShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EShop.Model.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("EShop.Model.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EShop.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3280),
                            Description = "各類電子設備",
                            Name = "電子產品"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3280),
                            Description = "各類書籍",
                            Name = "圖書"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3280),
                            Description = "衣服和鞋類",
                            Name = "服裝"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3290),
                            Description = "家庭用品",
                            Name = "家居用品"
                        });
                });

            modelBuilder.Entity("EShop.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 14, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3450),
                            Status = "Delivered",
                            TotalPrice = 1599.97m,
                            UpdatedAt = new DateTime(2026, 1, 19, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3460),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 21, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3460),
                            Status = "Shipped",
                            TotalPrice = 99.98m,
                            UpdatedAt = new DateTime(2026, 1, 23, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3460),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("EShop.Model.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            TotalPrice = 999.99m,
                            UnitPrice = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 6,
                            Quantity = 3,
                            TotalPrice = 59.97m,
                            UnitPrice = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 2,
                            TotalPrice = 99.98m,
                            UnitPrice = 49.99m
                        });
                });

            modelBuilder.Entity("EShop.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3310),
                            Description = "最新款蘋果手機，配備 A17 Pro 晶片",
                            Name = "iPhone 15 Pro",
                            Price = 999.99m,
                            Stock = 50,
                            UpdatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3310)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3310),
                            Description = "高效能筆記本電腦，適合專業工作",
                            Name = "MacBook Pro 16",
                            Price = 2499.99m,
                            Stock = 20,
                            UpdatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3310)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3310),
                            Description = "輕薄平板電腦，適合娛樂和工作",
                            Name = "iPad Air",
                            Price = 599.99m,
                            Stock = 35,
                            UpdatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3310)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3320),
                            Description = "深入學習 C# 程式設計",
                            Name = "C# 完全指南",
                            Price = 49.99m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3320)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3320),
                            Description = "學習如何使用 .NET Core 開發應用",
                            Name = ".NET Core 實戰",
                            Price = 59.99m,
                            Stock = 80,
                            UpdatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3320)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3320),
                            Description = "舒適的棉質 T 恤",
                            Name = "T恤",
                            Price = 19.99m,
                            Stock = 200,
                            UpdatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3320)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3350),
                            Description = "經典牛仔褲",
                            Name = "牛仔褲",
                            Price = 79.99m,
                            Stock = 150,
                            UpdatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3350)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3350),
                            Description = "全自動咖啡機",
                            Name = "咖啡機",
                            Price = 129.99m,
                            Stock = 40,
                            UpdatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3350)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3350),
                            Description = "LED 護眼台燈",
                            Name = "台燈",
                            Price = 39.99m,
                            Stock = 60,
                            UpdatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3350)
                        });
                });

            modelBuilder.Entity("EShop.Model.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3180),
                            Description = "管理員",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3190),
                            Description = "客戶",
                            Name = "Customer"
                        });
                });

            modelBuilder.Entity("EShop.Model.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            Id = 0
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2,
                            Id = 0
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2,
                            Id = 0
                        });
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3410),
                            Email = "admin@example.com",
                            IsActive = true,
                            Name = "管理員",
                            PasswordHash = "hashed_password_123",
                            UpdatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3410)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3420),
                            Email = "customer1@example.com",
                            IsActive = true,
                            Name = "客戶一",
                            PasswordHash = "hashed_password_456",
                            UpdatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3420)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3420),
                            Email = "customer2@example.com",
                            IsActive = true,
                            Name = "客戶二",
                            PasswordHash = "hashed_password_789",
                            UpdatedAt = new DateTime(2026, 1, 24, 6, 49, 3, 224, DateTimeKind.Utc).AddTicks(3420)
                        });
                });

            modelBuilder.Entity("EShop.Model.Cart", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Model.CartItem", b =>
                {
                    b.HasOne("EShop.Model.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Model.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Model.Order", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Model.OrderItem", b =>
                {
                    b.HasOne("EShop.Model.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Model.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Model.Product", b =>
                {
                    b.HasOne("EShop.Model.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EShop.Model.UserRole", b =>
                {
                    b.HasOne("EShop.Model.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Model.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EShop.Model.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EShop.Model.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EShop.Model.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EShop.Model.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
