// <auto-generated />
using System;
using EShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("EShop.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("EShop.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("EShop.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2600),
                            Description = "各類電子設備",
                            Name = "電子產品"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2600),
                            Description = "各類書籍",
                            Name = "圖書"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2610),
                            Description = "衣服和鞋類",
                            Name = "服裝"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2610),
                            Description = "家庭用品",
                            Name = "家居用品"
                        });
                });

            modelBuilder.Entity("EShop.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 30, 3, 27, 7, 891, DateTimeKind.Utc).AddTicks(2210),
                            Status = "Delivered",
                            TotalPrice = 1599.97m,
                            UpdatedAt = new DateTime(2026, 2, 4, 3, 27, 7, 891, DateTimeKind.Utc).AddTicks(2220),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 6, 3, 27, 7, 891, DateTimeKind.Utc).AddTicks(2220),
                            Status = "Shipped",
                            TotalPrice = 99.98m,
                            UpdatedAt = new DateTime(2026, 2, 8, 3, 27, 7, 891, DateTimeKind.Utc).AddTicks(2220),
                            UserId = 3
                        });
                });

            modelBuilder.Entity("EShop.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            TotalPrice = 999.99m,
                            UnitPrice = 999.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 6,
                            Quantity = 3,
                            TotalPrice = 59.97m,
                            UnitPrice = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 2,
                            TotalPrice = 99.98m,
                            UnitPrice = 49.99m
                        });
                });

            modelBuilder.Entity("EShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2650),
                            Description = "最新款蘋果手機，配備 A17 Pro 晶片",
                            Name = "iPhone 15 Pro",
                            Price = 999.99m,
                            Stock = 50,
                            UpdatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2650)
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2660),
                            Description = "高效能筆記本電腦，適合專業工作",
                            Name = "MacBook Pro 16",
                            Price = 2499.99m,
                            Stock = 20,
                            UpdatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2660)
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2660),
                            Description = "輕薄平板電腦，適合娛樂和工作",
                            Name = "iPad Air",
                            Price = 599.99m,
                            Stock = 35,
                            UpdatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2660)
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2660),
                            Description = "深入學習 C# 程式設計",
                            Name = "C# 完全指南",
                            Price = 49.99m,
                            Stock = 100,
                            UpdatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2660)
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2670),
                            Description = "學習如何使用 .NET Core 開發應用",
                            Name = ".NET Core 實戰",
                            Price = 59.99m,
                            Stock = 80,
                            UpdatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2670)
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2670),
                            Description = "舒適的棉質 T 恤",
                            Name = "T恤",
                            Price = 19.99m,
                            Stock = 200,
                            UpdatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2670)
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2670),
                            Description = "經典牛仔褲",
                            Name = "牛仔褲",
                            Price = 79.99m,
                            Stock = 150,
                            UpdatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2670)
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2670),
                            Description = "全自動咖啡機",
                            Name = "咖啡機",
                            Price = 129.99m,
                            Stock = 40,
                            UpdatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2670)
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2680),
                            Description = "LED 護眼台燈",
                            Name = "台燈",
                            Price = 39.99m,
                            Stock = 60,
                            UpdatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2680)
                        });
                });

            modelBuilder.Entity("EShop.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2450),
                            Description = "管理員",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 778, DateTimeKind.Utc).AddTicks(2460),
                            Description = "客戶",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("EShop.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "30d74e3e-7f1e-4087-a9b7-84b6e0891232",
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 815, DateTimeKind.Utc).AddTicks(8690),
                            Email = "admin@example.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = true,
                            Name = "管理員",
                            NormalizedEmail = "ADMIN@EXAMPLE.COM",
                            NormalizedUserName = "ADMIN@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEF6CO6xQePeQ91j73ze4L4Z1o5YkTdfIh9zryrwTL6mIVXSGl3at1PxZuBSWgEQFtA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "663c086f-089b-4d16-b564-62e10f32bbc2",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 815, DateTimeKind.Utc).AddTicks(8690),
                            UserName = "admin@example.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cb4756b6-0445-435b-92c7-3b5bddb645ea",
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 853, DateTimeKind.Utc).AddTicks(6280),
                            Email = "customer1@example.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = true,
                            Name = "客戶一",
                            NormalizedEmail = "CUSTOMER1@EXAMPLE.COM",
                            NormalizedUserName = "CUSTOMER1@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGIipTvWitCHb4U4F1Tl8oW3Nk3iyK4jbtvg/ZyefJt/cLh4NPYb5uk1E/XaXcwmiw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "74c519e2-487b-431a-801d-eaf547e5e146",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 853, DateTimeKind.Utc).AddTicks(6280),
                            UserName = "customer1@example.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "81ba3af7-e8d3-45c7-8b18-98900bf1d053",
                            CreatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 891, DateTimeKind.Utc).AddTicks(1760),
                            Email = "customer2@example.com",
                            EmailConfirmed = true,
                            IsActive = true,
                            LockoutEnabled = true,
                            Name = "客戶二",
                            NormalizedEmail = "CUSTOMER2@EXAMPLE.COM",
                            NormalizedUserName = "CUSTOMER2@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBxTj7YbJhn0C6uVAgDaQVT28svF9fJKFiV0z9EI0ovupAUHmE1FbEwBxOyxkNE09g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1a3ecce9-0212-42a9-b37b-1d9bb7ac57a5",
                            TwoFactorEnabled = false,
                            UpdatedAt = new DateTime(2026, 2, 9, 3, 27, 7, 891, DateTimeKind.Utc).AddTicks(1760),
                            UserName = "customer2@example.com"
                        });
                });

            modelBuilder.Entity("EShop.Models.Cart", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Models.CartItem", b =>
                {
                    b.HasOne("EShop.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Models.Order", b =>
                {
                    b.HasOne("User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EShop.Models.OrderItem", b =>
                {
                    b.HasOne("EShop.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EShop.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("EShop.Models.Product", b =>
                {
                    b.HasOne("EShop.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EShop.Models.UserRole", b =>
                {
                    b.HasOne("EShop.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("EShop.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EShop.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("EShop.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("EShop.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EShop.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EShop.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
